---
title: "exploration"
author: "Evan Roybal"
date: "2/10/2022"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loading Packages
```{r}
library(tidyverse)
library(naniar)
library(janitor)
library(skimr)
library(shiny)
library(shinydashboard)
library(lubridate)
library(ggmap)
```

```{r}
getwd ()
```


loading dataset 
```{r}
#toxicity <- read.csv('toxicitydata_2022-01-07.csv')

#toxicity <- toxicity %>%
#  clean_names()

#head(toxicity)

#toxicity_short <- toxicity %>%
#  filter(near(latitude, 38.73, tol = 1), near(longitude, #-121.81, tol = 1))
#toxicity_short

#toxicity_davis <- toxicity %>%
#  filter(str_detect(sample_agency, "University of California Davis-Aquatic Toxicology Lab"))

#nrow(toxicity_davis)

#colnames(toxicity_davis)

#head

#toxicity_davis <- toxicity_davis %>%
#  select(-c(station_code, location_code, sample_type_code, lab_sample_id, batch_verification_code, compliance_code, sample_comments, collection_comments, tox_test_comments, time_point_comments, tox_result_comments, tox_batch_comments, event_code, protocol_code, lab_submission_code, location_detail_wq_comments, sample_id))
         
#table(toxicity_davis$sample_agency)

#write.csv(toxicity_davis, file = "toxicity_davis.csv")

```

```{r}
taxda <- readr::read_csv("toxicity_davis.csv")
glimpse(taxda)
```

```{r}
taxda %>%
  filter(latitude != -88) %>%
  filter(longitude != -88) %>%
  select(latitude, longitude) %>%
  summary()
```

```{r}
taxda_map <- taxda %>%
  filter(latitude != -88) %>%
  filter(longitude != -88) 
```


```{r}
lat <- c(37.27 ,40.96)
long <- c(-122.5  , -120.4 )
bbox <- make_bbox(long, lat, f = 0.05)
```

```{r}
map1 <- get_map(bbox, maptype = "terrain", source = "stamen")
ggmap(map1)
```
```{r}
ggmap(map1) + 
  geom_point(data = taxda, aes(longitude, latitude)) +
  labs(x = "Longitude", y = "Latitude", title = "Locations")
```

```{r}
library(albersusa)
us_comp <- usa_sf()
cnty_comp <- counties_sf()

ca_comp <- us_comp %>%
  filter(name=="California")
ca_cnty_comp <- cnty_comp %>% 
  filter(state=="California")
ggplot() +
  geom_sf(data = ca_comp, size = 0.125)+
  geom_sf(data = ca_cnty_comp, size = 0.125)+
  geom_point(data = taxda_map, aes(longitude, latitude))
```


### Evan's data explorations (sorry for the mess)
```{r}
nrow(taxda)

colnames(taxda)
n_unique(taxda$station_name)
n_unique(taxda$project)
```

```{r}
project_frequency <- taxda %>%
  select(project) %>%
  ggplot(aes(x = project)) +
  geom_bar() +
  coord_flip()
project_frequency
```

focusing on pelagic organism decline
```{r}
pelagic_org <- taxda %>%
  filter(grepl('Pelagic', project))

nrow(pelagic_org)

#this makes up the majority of the data and could be used for a specific analysis that targets the ocean
```

```{r}
taxda %>%
  ggplot(aes(x = organism_name)) +
  geom_bar() +
  coord_flip()
```
Potential heat map for organism abundance?
Could also focus on Hyalella azteca

Sounds Good


```{r}
pelagic_pH <- pelagic_org %>%
  filter(analyte == 'pH')

nrow(pelagic_pH)
head(pelagic_pH)

pelagic_pH %>%
  filter((sample_date) <= 2020) %>%
  ggplot(aes(x = sample_date, y = result)) +
  geom_line() +
  geom_smooth() +
  labs(title = 'pH over time')
#not really sure how to cap it at 2010 since I don't know how to filter dates
```

```{r}
typeof(taxda$result)
```

```{r}

```




Not Working ATM
```{r}
ui <- fluidPage(    
  
  titlePanel("Log 10 Homerange by Locomotion"), # give the page a title
  
  # generate a row with a sidebar
  sidebarLayout(      
    
  # define the sidebar with one input
  sidebarPanel(
  selectInput("Analyte", " Select Analyte of Interest:", choices=unique(taxda$analyte)), hr()),
    
  # create a spot for the barplot
  mainPanel(
  plotOutput("anyPlot"))
  )
  )

  # define a server for the Shiny app
  server <- function(input, output, session) {
  
  # fill in the spot we created for a plot
  output$anyPlot <- renderPlot({
    
    taxda_sep %>% 
    filter(analyte == input$analyte) %>%
    ggplot(aes_string(x=year, y = result)) + 
    geom_line()
  })
  }

shinyApp(ui, server)

```

## Other Analysis

```{r}
taxda_sep <- taxda %>%
    separate(sample_date, into = c("year", "month", "date"), sep="-") 
pelagic_org2 <- taxda_sep %>%
  filter(grepl('Pelagic', project))
pelagic_pH2 <- pelagic_org2 %>%
  filter(analyte == 'pH')


pelagic_pH %>%
  filter(year <= 2010) %>%
  ggplot(aes(x = year, y = result)) +
  geom_boxplot() +
  geom_smooth() +
  labs(title = 'pH over time')
```




```{r}
pelagic_pH %>%
  group_by(year) %>%
  summarise(mean_res = mean(result)) %>%
  ggplot(aes(x = year, y = mean_res, group =1)) +
  geom_line() +
  geom_smooth() +
  labs(title = 'pH over time')
```

```{r}
taxda_sep %>%
  group_by(organism_name) %>%
  filter(result != "NA") %>%
  summarise(mean_result = mean(result)) 
  
```

```{r}
taxda_sep %>%
  filter(result != "NA") %>%
   ggplot(aes(x=organism_name, y=result, fill=collection_method_name)) + 
  geom_boxplot()+ 
  facet_wrap(~collection_method_name, ncol=)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  scale_y_log10()+
  coord_flip()
```

Test