---
title: "Sac River Watershed"
author: "Colin Lauffer"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sac River

library
```{r}
library(tidyverse)
```

### loading data
```{r}
taxda <- readr::read_csv("data/toxicity_davis.csv")
taxda_sep <- taxda %>%
    separate(sample_date, into = c("year", "month", "date"), sep="-") 
taxda_sepyr <- taxda_sep %>% 
  mutate(year_num = as.numeric(year))
taxda_sac <- taxda_sepyr %>%
  filter(grepl('Sac', project)) 
#write.csv(taxda_sac,file = 'sac_org.csv')

```

### Brief Analysis
```{r}
taxda_sac %>%
  count(collection_depth)
```

### Counting Orgnaisms
```{r}
taxda_sac %>%
  ggplot(aes(x=organism_name, y= )) +
  geom_boxplot()
```




### Faceting
```{r}
taxda_sac %>%
  filter(result < 100) %>%
  ggplot(aes(x=analyte,y = result, fill = organism_name))+
  geom_violin(alpha = .3, na.rm = TRUE) +
  geom_boxplot(alpha = .4)+
  theme_classic()+
  facet_wrap(~organism_name)+
  scale_y_log10()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  labs(title = "Result by Analyte and Organism",
       x = NULL,
       y = "Result",
       fill = "Organism Name")
  

```



### Over time